# Generated by Django 4.2.5 on 2024-02-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResidentManager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'ASSIGNED'), ('work progress', 'WORK PROGRESS'), ('done', 'DONE')], default=None, max_length=20)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManager.servicecategory')),
                ('house_no', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ResidentManager.house')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManager.serviceproviders')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_desc', models.CharField(default=None, max_length=250)),
                ('request_status', models.CharField(choices=[('pending', 'PENDING'), ('cleared', 'CLEARED')], default=None, max_length=8)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManager.house')),
                ('service_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManager.servicecategory')),
                ('tenant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResidentManager.tenants')),
            ],
        ),
    ]
